version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1

