version: '3'

services:
  nutch:
    image: ynishi/nutch
    volumes:
      - ./urls:/root/urls
      - ./crawl:/root/crawl
    command: nutch/bin/crawl -i -s urls/seed.txt crawl 1
    links:
      - elasticsearch:elasticsearch
      - httpd:httpd
  elasticsearch:
    image: ynishi/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      - ./es_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
  kibana:
    image: kibana:5.3.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elastic:pass@elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
  httpd:
    image: ynishi/htmlserver
    command: -p 80 run
    ports:
      - 80:80
    volumes:
      - ./htdocs:/html
